const $=s=>document.querySelector(s);let invites=[];
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Ошибка');return data}
async function init(){const s=await api('/api/admin/session');if(s.authenticated)showDashboard()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target).entries()))});showDashboard()}catch(err){$('#loginMessage').textContent=err.message}})
async function showDashboard(){$('#loginView').classList.add('hidden');$('#dashboard').classList.remove('hidden');await loadInvites()}
async function loadInvites(){invites=await api('/api/admin/invites');render()}
function render(){const q=$('#search').value.toLowerCase();const list=invites.filter(i=>i.guestNames.toLowerCase().includes(q));const yes=invites.filter(i=>i.response?.attendance==='yes').length;const no=invites.filter(i=>i.response?.attendance==='no').length;const pending=invites.length-yes-no;$('#stats').innerHTML=[['Всего',invites.length],['Будут',yes],['Не будут',no],['Нет ответа',pending]].map(([a,b])=>`<div class="stat"><span>${a}</span><strong>${b}</strong></div>`).join('');$('#inviteRows').innerHTML=list.map(i=>{const st=i.response?.attendance==='yes'?['Будет','yes']:i.response?.attendance==='no'?['Не будет','no']:['Нет ответа','pending'];return `<tr><td><strong>${esc(i.guestNames)}</strong><br><small>${esc(i.greeting)}</small></td><td><span class="badge ${st[1]}">${st[0]}</span></td><td>${i.response?`${esc(i.response.firstName)} ${esc(i.response.lastName)}`:'—'}</td><td><div class="link-group"><button class="mini" onclick="copyLink('${i.url}')">Копировать</button><a class="mini ghost" target="_blank" href="${i.url}">Открыть</a></div></td><td>${i.response?`<button class="mini ghost" onclick="resetResponse('${i.id}')">Сбросить</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="5">Приглашений пока нет.</td></tr>'}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.copyLink=async url=>{await navigator.clipboard.writeText(url);alert('Ссылка скопирована')};window.resetResponse=async id=>{if(confirm('Удалить ответ гостя?')){await api(`/api/admin/invites/${id}/response`,{method:'DELETE'});loadInvites()}}
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();try{const created=await api('/api/admin/invites',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target).entries()))});$('#createdLink').innerHTML=`Ссылка создана: <strong>${created.url}</strong>`;e.target.reset();e.target.greeting.value='Дорогие гости';loadInvites()}catch(err){alert(err.message)}})
$('#search').addEventListener('input',render);$('#logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()});init();
